default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: mak4alex
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: chatty_development

test:
  <<: *default
  database: chatty_test

production:
  adapter: mysql2
  encoding: utf8
  host:     <%= ENV["DATABASE_HOST"] %>
  port:     <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USER_NAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>
